# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# describe LessonPlansController do

#   # This should return the minimal set of attributes required to create a valid
#   # LessonPlan. As you add validations to LessonPlan, be sure to
#   # update the return value of this method accordingly.
#   def valid_attributes
#     { "name" => "MyString" }
#   end

#   # This should return the minimal set of values that should be in the session
#   # in order to pass any filters (e.g. authentication) defined in
#   # LessonPlansController. Be sure to keep this updated too.
#   def valid_session
#     {}
#   end

#   describe "GET index" do
#     it "assigns all lesson_plans as @lesson_plans" do
#       lesson_plan = LessonPlan.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:lesson_plans).should eq([lesson_plan])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested lesson_plan as @lesson_plan" do
#       lesson_plan = LessonPlan.create! valid_attributes
#       get :show, {:id => lesson_plan.to_param}, valid_session
#       assigns(:lesson_plan).should eq(lesson_plan)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new lesson_plan as @lesson_plan" do
#       get :new, {}, valid_session
#       assigns(:lesson_plan).should be_a_new(LessonPlan)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested lesson_plan as @lesson_plan" do
#       lesson_plan = LessonPlan.create! valid_attributes
#       get :edit, {:id => lesson_plan.to_param}, valid_session
#       assigns(:lesson_plan).should eq(lesson_plan)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new LessonPlan" do
#         expect {
#           post :create, {:lesson_plan => valid_attributes}, valid_session
#         }.to change(LessonPlan, :count).by(1)
#       end

#       it "assigns a newly created lesson_plan as @lesson_plan" do
#         post :create, {:lesson_plan => valid_attributes}, valid_session
#         assigns(:lesson_plan).should be_a(LessonPlan)
#         assigns(:lesson_plan).should be_persisted
#       end

#       it "redirects to the created lesson_plan" do
#         post :create, {:lesson_plan => valid_attributes}, valid_session
#         response.should redirect_to(LessonPlan.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved lesson_plan as @lesson_plan" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         LessonPlan.any_instance.stub(:save).and_return(false)
#         post :create, {:lesson_plan => { "name" => "invalid value" }}, valid_session
#         assigns(:lesson_plan).should be_a_new(LessonPlan)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         LessonPlan.any_instance.stub(:save).and_return(false)
#         post :create, {:lesson_plan => { "name" => "invalid value" }}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested lesson_plan" do
#         lesson_plan = LessonPlan.create! valid_attributes
#         # Assuming there are no other lesson_plans in the database, this
#         # specifies that the LessonPlan created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         LessonPlan.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
#         put :update, {:id => lesson_plan.to_param, :lesson_plan => { "name" => "MyString" }}, valid_session
#       end

#       it "assigns the requested lesson_plan as @lesson_plan" do
#         lesson_plan = LessonPlan.create! valid_attributes
#         put :update, {:id => lesson_plan.to_param, :lesson_plan => valid_attributes}, valid_session
#         assigns(:lesson_plan).should eq(lesson_plan)
#       end

#       it "redirects to the lesson_plan" do
#         lesson_plan = LessonPlan.create! valid_attributes
#         put :update, {:id => lesson_plan.to_param, :lesson_plan => valid_attributes}, valid_session
#         response.should redirect_to(lesson_plan)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the lesson_plan as @lesson_plan" do
#         lesson_plan = LessonPlan.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         LessonPlan.any_instance.stub(:save).and_return(false)
#         put :update, {:id => lesson_plan.to_param, :lesson_plan => { "name" => "invalid value" }}, valid_session
#         assigns(:lesson_plan).should eq(lesson_plan)
#       end

#       it "re-renders the 'edit' template" do
#         lesson_plan = LessonPlan.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         LessonPlan.any_instance.stub(:save).and_return(false)
#         put :update, {:id => lesson_plan.to_param, :lesson_plan => { "name" => "invalid value" }}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested lesson_plan" do
#       lesson_plan = LessonPlan.create! valid_attributes
#       expect {
#         delete :destroy, {:id => lesson_plan.to_param}, valid_session
#       }.to change(LessonPlan, :count).by(-1)
#     end

#     it "redirects to the lesson_plans list" do
#       lesson_plan = LessonPlan.create! valid_attributes
#       delete :destroy, {:id => lesson_plan.to_param}, valid_session
#       response.should redirect_to(lesson_plans_url)
#     end
#   end

# end
